name: airflights-clojure

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - name: Install dependencies
      run: lein deps
    - name: Run tests
      run: lein test
    - name: Run Coverage
      run: lein cloverage --lcov
    - name: Run Plugin
      run: lein omni-coveragereporter-lein
      env:
         COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
         CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
         CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
